// Exemplo de mock de dados para dashboard de ordens de serviço
// Não está mais sendo utilizado no App principal

export const MOCK_DATA = {
  total: 200,
  abertas: 40,
  andamento: 30,
  fechadas: 130,
  tempoMedio: 6.5,
  tecnicoMaisConcluidas: 'João Silva',
  ordensUltimaSemana: 22,
  diasUltimaParada: 3,
  osCorretivasMes: 55,
  osPreventivaMes: 38,
  osMelhoriaMes: 12,
  osEstrategicaMes: 25,
  osPreditivaMes: 18,
  chartsData: {
    volumePorStatus: [
      { name: 'Abertas', value: 40 },
      { name: 'Em Andamento', value: 30 },
      { name: 'Fechadas', value: 130 },
    ],
    percentualPorStatus: [
      { name: 'Abertas', value: 20 },
      { name: 'Em Andamento', value: 15 },
      { name: 'Fechadas', value: 65 },
    ],
    tendenciaVolume: [
      { name: 'Jan', abertas: 10, andamento: 5, fechadas: 20 },
      { name: 'Fev', abertas: 12, andamento: 7, fechadas: 22 },
      { name: 'Mar', abertas: 15, andamento: 8, fechadas: 25 },
      { name: 'Abr', abertas: 8, andamento: 6, fechadas: 18 },
      { name: 'Mai', abertas: 14, andamento: 4, fechadas: 30 },
    ],
    equipamentoMaisHoras: [
      { name: 'Esteira 1', value: 120 },
      { name: 'Prensa 2', value: 95 },
      { name: 'Compressor', value: 80 },
      { name: 'Forno', value: 60 },
      { name: 'Empilhadeira', value: 45 },
    ],
    volumePorTipo: [
      { name: 'Corretiva', value: 90 },
      { name: 'Preventiva', value: 70 },
      { name: 'Preditiva', value: 40 },
      { name: 'Estratégica', value: 25 },
    ],
    osPorEquipamento: [
      { name: 'Esteira 1', value: 14 },
      { name: 'Prensa 2', value: 11 },
      { name: 'Compressor', value: 9 },
      { name: 'Forno', value: 7 },
      { name: 'Empilhadeira', value: 6 },
    ],
    topMecanicos: [
      { name: 'João Silva', value: 18 },
      { name: 'Carlos Souza', value: 15 },
      { name: 'Pedro Lima', value: 13 },
      { name: 'Lucas Alves', value: 10 },
      { name: 'Rafael Costa', value: 8 },
    ],
    topEletricistas: [
      { name: 'Marcos Dias', value: 16 },
      { name: 'André Silva', value: 14 },
      { name: 'Bruno Rocha', value: 12 },
      { name: 'Felipe Ramos', value: 9 },
      { name: 'Tiago Pinto', value: 7 },
    ],
    topSupervisores: [
      { name: 'Ana Paula', value: 20 },
      { name: 'Fernanda Lima', value: 17 },
      { name: 'Juliana Souza', value: 15 },
      { name: 'Patrícia Gomes', value: 12 },
      { name: 'Roberta Dias', value: 10 },
    ],
    topSupervisoresConcluirOS: [
      { name: 'Ana Paula', value: 20 },
      { name: 'Fernanda Lima', value: 17 },
      { name: 'Juliana Souza', value: 15 },
      { name: 'Patrícia Gomes', value: 12 },
      { name: 'Roberta Dias', value: 10 },
    ],
    horasPorFuncionario: [
      { nome: 'Luigi', disponiveis: 80, realizadas: 58 },
      { nome: 'Maria', disponiveis: 76, realizadas: 62 },
      { nome: 'João', disponiveis: 90, realizadas: 70 },
      { nome: 'Ana', disponiveis: 85, realizadas: 75 },
      { nome: 'Carlos', disponiveis: 78, realizadas: 60 },
      { nome: 'Fernanda', disponiveis: 82, realizadas: 68 },
      { nome: 'Paulo', disponiveis: 88, realizadas: 72 },
      { nome: 'Juliana', disponiveis: 75, realizadas: 66 },
      { nome: 'Rafael', disponiveis: 92, realizadas: 74 },
      { nome: 'Patrícia', disponiveis: 80, realizadas: 65 },
      { nome: 'Roberta', disponiveis: 84, realizadas: 69 },
      { nome: 'Bruno', disponiveis: 77, realizadas: 73 },
      { nome: 'Felipe', disponiveis: 79, realizadas: 67 },
      { nome: 'Tiago', disponiveis: 81, realizadas: 71 },
      { nome: 'Lucas', disponiveis: 86, realizadas: 64 },
      { nome: 'André', disponiveis: 74, realizadas: 76 },
      { nome: 'Marcos', disponiveis: 83, realizadas: 77 },
      { nome: 'Pedro', disponiveis: 87, realizadas: 63 },
      { nome: 'Aline', disponiveis: 73, realizadas: 61 },
      { nome: 'Sofia', disponiveis: 89, realizadas: 59 },
    ],
  },
};
